version: '3.1'

services:

# The mongo db
  mongo:
    image: mongo
#    ports:
#      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s3cr3t

# The mongo GUI running on http://localhost:8081
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: s3cr3t

# The reborn2020 application
  reborn2020:
    build:
      dockerfile: Dockerfile
      context: ./
    image: reborn2020
    ports:
    - 5000:5000
    depends_on:
      - mongo
    links:
      - mongo
